language: scala
sudo: true
dist: trusty
addons:
  apt:
    update: true
    packages:
    - numactl
    - libnuma1
    - libnuma-dev
    - libnuma-dbg
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
  - $HOME/ssl
  - $HOME/mongodb-linux-x86_64-2.6.12
  - $HOME/mongodb-linux-x86_64-amazon-3.2.10
  - $HOME/mongodb-linux-x86_64-amazon-3.6.5
scala:
- 2.12.6
- 2.11.12
jdk:
- openjdk7
env:
  - CI_CATEGORY=UNIT_TESTS
  - CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.3.13 ITERATEES_VERSION=2.3.8 MONGO_PROFILE=default MONGO_VER=2_6
before_install:
  - ./.ci_scripts/beforeInstall.sh $CI_CATEGORY $MONGO_VER $MONGO_PROFILE /tmp/integration-env.sh
  - if [ "x$CI_CATEGORY" = "xINTEGRATION_TESTS" ]; then (./.ci_scripts/fork-mongod.sh /tmp/integration-env.sh); fi
script:
  - export SCALA_VERSION="$TRAVIS_SCALA_VERSION"
  - if [[ "${TRAVIS_JDK_VERSION}" == "openjdk7" ]]; then echo "-XX:MaxPermSize=1024m" >> .jvmopts ; fi
  - ./.ci_scripts/retry.sh 3 ./.ci_scripts/validate.sh /tmp/integration-env.sh
after_success: ./.ci_scripts/afterSuccess.sh
